print("Ejercicio 1:")
print("Hola mundo")
print("Ejercicio 2:")
v=("Hola mundo en una variable")
print(v)
print("Ejercicio 3:")
nom=raw_input("Cual es tu nombre ")
print("hola "+nom)
print("Ejercicio 4:")
n=input("Ingresa un numero")
for i in range(n):
    print(nom)
print("Ejercicio 5:")
nm=nom.upper()
lon=str(len(nom))
print(nm+" Tiene "+lon+" letras")
